// <auto-generated />
using System;
using Conexao.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Conexao.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Conexao.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email_Cliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imei_Cliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nascimento_Cliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<int?>("Plano_Cliente")
                        .HasColumnType("int");

                    b.Property<string>("Sexo_Cliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone_Cliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Conexao.Models.Contato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("Nome_Contato")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tel_contato")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Contato");
                });

            modelBuilder.Entity("Conexao.Models.Imagens", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("Imagem")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Imagens");
                });

            modelBuilder.Entity("Conexao.Models.LogMovimentacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("Latitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Longitude")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("LogMovimentacao");
                });

            modelBuilder.Entity("Conexao.Models.Pagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("DtPagamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MrPagamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PxPagamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusPagId")
                        .HasColumnType("int");

                    b.Property<int?>("StatusPagamentoId")
                        .HasColumnType("int");

                    b.Property<float?>("VlPagamento")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("StatusPagamentoId");

                    b.ToTable("Pagamento");
                });

            modelBuilder.Entity("Conexao.Models.Registro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Latitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Longitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MtRegistrado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MtRegistro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TiposOcorrenciasId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TiposOcorrenciasId");

                    b.ToTable("Registro");
                });

            modelBuilder.Entity("Conexao.Models.Relacionamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("FimRelacionamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InRelacionamento")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Relacionamento");
                });

            modelBuilder.Entity("Conexao.Models.StatusPagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("dsStatusPagamento")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StatusPagamentos");
                });

            modelBuilder.Entity("Conexao.Models.TipoRelacionamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("DsTipoRelacionamento")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipoRelacionamento");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DsTipoRelacionamento = "Standard"
                        },
                        new
                        {
                            Id = 2,
                            DsTipoRelacionamento = "Premium"
                        });
                });

            modelBuilder.Entity("Conexao.Models.TiposOcorrencias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("dsTiposOcorrencias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("icTipoOcorrencia")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.ToTable("TiposOcorrencias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            dsTiposOcorrencias = "Furto"
                        },
                        new
                        {
                            Id = 2,
                            dsTiposOcorrencias = "Agressão"
                        },
                        new
                        {
                            Id = 3,
                            dsTiposOcorrencias = "Assédio"
                        },
                        new
                        {
                            Id = 4,
                            dsTiposOcorrencias = "Roubo"
                        });
                });

            modelBuilder.Entity("Conexao.Models.Contato", b =>
                {
                    b.HasOne("Conexao.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Conexao.Models.Imagens", b =>
                {
                    b.HasOne("Conexao.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Conexao.Models.LogMovimentacao", b =>
                {
                    b.HasOne("Conexao.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Conexao.Models.Pagamento", b =>
                {
                    b.HasOne("Conexao.Models.Cliente", "CLiente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Conexao.Models.StatusPagamento", "StatusPagamento")
                        .WithMany()
                        .HasForeignKey("StatusPagamentoId");

                    b.Navigation("CLiente");

                    b.Navigation("StatusPagamento");
                });

            modelBuilder.Entity("Conexao.Models.Registro", b =>
                {
                    b.HasOne("Conexao.Models.TiposOcorrencias", "TiposOcorrencias")
                        .WithMany()
                        .HasForeignKey("TiposOcorrenciasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TiposOcorrencias");
                });

            modelBuilder.Entity("Conexao.Models.Relacionamento", b =>
                {
                    b.HasOne("Conexao.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });
#pragma warning restore 612, 618
        }
    }
}
